services:
  server:
    build: .
    ports:
      - 80:80
    environment:
      - DB_PATH=${DB_PATH}
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    volumes:
      - ../db/litlog.db:/app/db/litlog.db
      - ../dist:/app/dist
