version: "3"

vars:
  NAME: lit-log

dotenv: [".env"]

tasks:
  clean:
    cmds:
      - cmd: rm -f -R build
        ignore_error: true

  run:
    env:
      CGO_ENABLED: 1
      GODEBUG: cgocheck=0
    cmds:
      - go run --race -v cmd/main.go

  build:
    cmd:
      task: build_linux

  build_linux:
    env:
      GOARCH: amd64
      GOOS: linux
      GODEBUG: cgocheck=0
    cmds:
      - cmd: mkdir build
        ignore_error: true
      - go build -v -o build/{{.NAME}} cmd/main.go

  # publish:
  #   cmds:
  #     - cmd: scp -P $SSH_PORT C:\Users\Марат\Downloads\litlog.tar root@1acc07ed7a30.vps.myjino.ru:/home
